In [4]:
import csv
import numpy as np
import pandas as pd
from pandas import Series,DataFrame

In [5]:
df1 = pd.read_csv('allSuzuki.csv',encoding='cp932')
df1.head()

name  likeDL  Interest  toUse  investigate  pleasant
0  鈴木1       1         0      1            0         1
1  鈴木2       0         1      0            0         0
2  鈴木3       0         1      1            1         0
3  鈴木4       0         0      1            0         0
4  鈴木5       1         0      1            1         1

In [7]:
x = np.array([[1,0],[0,1]])

In [9]:
t = np.array([1,0])

In [10]:
t

array([1, 0])

In [11]:
def sigmoid(x):
    return 1/(1+np.exp(-x))

In [12]:
def sigmoid_der(x):
    return (1-sigmoid(x)) * sigmoid(x)

In [45]:
lr = 0.5
x  = np.array([[1,0],[1,0],[0,0],[0,0],[1,1],[1,1],[1,1]])
w = np.array([0.1, 0.1])
y  = np.array([1,1,0,0,1,1,1])
h=0
y_hat=0
error=0
error_term=0
del_w=0

In [46]:
for var,ans in zip(x,y):
    h = np.dot(var,w)  #入力層の総和
    y_hat = sigmoid(h)  #シグモイド関数で計算した
    error = ans - y_hat      #誤差
    error_term = error * sigmoid_der(h) #誤差項
    del_w = lr * error_term * var                 #デルタwを求めた
    w += del_w                                          #wに数値を計算

In [47]:
w

array([0.3590882 , 0.24268738])

In [49]:
Y = df1.likeDL
Y.head()   #目的変数

0    1
1    0
2    0
3    0
4    1
Name: likeDL, dtype: int64

In [50]:
X = df1.drop(['likeDL'],axis=1)
X.head() #説明変数

name  Interest  toUse  investigate  pleasant
0  鈴木1         0      1            0         1
1  鈴木2         1      0            0         0
2  鈴木3         1      1            1         0
3  鈴木4         0      1            0         0
4  鈴木5         0      1            1         1

In [51]:
X = df1.drop(['name'],axis=1)
X.head() #説明変数

likeDL  Interest  toUse  investigate  pleasant
0       1         0      1            0         1
1       0         1      0            0         0
2       0         1      1            1         0
3       0         0      1            0         0
4       1         0      1            1         1

In [61]:
lr = 0.5
w = np.array([0.1, 0.1, 0.1 ,0.1])
h=0
y_hat=0
error=0
error_term=0
del_w=0

In [62]:
for var,ans in zip(X,Y):
    h = np.dot(var,w)  #入力層の総和
    y_hat = sigmoid(h)  #シグモイド関数で計算した
    error = ans - y_hat      #誤差
    error_term = error * sigmoid_der(h) #誤差項
    del_w = lr * error_term * var                 #デルタwを求めた
    w += del_w                                          #wに数値を計算

TypeError: Cannot cast array data from dtype('float64') to dtype('<U32') according to the rule 'safe'

In [60]:
X = X.drop(['likeDL'],axis=1)
X.head() #説明変数

Interest  toUse  investigate  pleasant
0         0      1            0         1
1         1      0            0         0
2         1      1            1         0
3         0      1            0         0
4         0      1            1         1

In [70]:
for var,ans in zip(X_test,Y):
    print (var)
    print(ans)

[0 1 0 1]
1
[1 0 0 0]
0
[1 1 1 0]
0
[0 1 0 0]
0
[0 1 1 1]
1
[0 0 0 0]
0
[0 0 1 1]
1
[1 1 1 1]
1
[0 1 1 0]
0
[1 1 0 0]
0
[0 1 0 0]
0
[1 1 0 1]
1
[1 0 0 0]
0
[0 0 0 1]
1
[0 1 0 0]
0
[1 1 0 1]
1
[1 0 0 0]
0
[1 0 1 0]
0
[0 0 1 0]
0
[0 1 0 1]
1
[0 1 1 0]
0
[1 1 1 0]
0
[1 0 0 1]
1
[1 0 0 1]
1
[0 1 0 1]
1
[1 0 0 1]
1
[0 0 0 0]
0
[1 1 0 0]
0
[1 0 1 0]
0
[1 1 0 0]
0
[0 0 0 0]
0
[1 0 0 0]
0
[0 0 0 1]
1
[1 1 0 0]
0
[1 0 1 0]
0
[1 1 1 0]
0
[1 0 0 1]
1
[1 0 0 1]
1
[0 1 1 0]
0
[1 0 0 1]
1
[0 1 0 1]
1
[1 1 1 0]
0
[1 1 0 0]
0
[1 1 0 1]
1
[1 0 0 0]
0
[0 1 1 0]
0
[1 0 1 1]
1
[0 1 0 1]
1
[1 0 1 1]
1
[1 0 0 0]
0
[1 1 1 1]
1
[1 0 1 1]
1
[1 1 0 1]
1
[0 1 0 0]
0
[1 1 1 1]
1
[0 1 0 1]
1
[0 1 1 1]
1
[0 0 0 1]
1
[1 1 0 0]
0
[1 0 1 0]
0
[1 1 0 1]
1
[0 1 1 1]
1
[1 0 1 1]
1
[1 0 0 0]
0
[1 1 1 1]
1
[0 0 1 1]
1
[0 0 1 0]
0
[1 0 1 0]
0
[1 0 0 1]
1
[1 0 1 0]
0
[1 0 0 1]
1
[0 0 1 1]
1
[0 0 0 0]
0
[0 0 1 0]
0
[1 1 1 0]
0
[0 0 0 0]
0
[1 1 1 0]
0
[1 1 0 1]
1
[1 0 1 0]
0
[1 0 1 1]
1
[0 1 1 1]
1
[1 0 1 0]
0
[0 0 1 0]
0
[0 1

In [67]:
X_test = X[['Interest','toUse','investigate','pleasant']].values

In [68]:
X_test

array([[0, 1, 0, 1],
       [1, 0, 0, 0],
       [1, 1, 1, 0],
       ...,
       [0, 1, 0, 1],
       [1, 0, 0, 1],
       [0, 0, 0, 1]])

In [71]:
for var,ans in zip(X_test,Y):
    h = np.dot(var,w)  #入力層の総和
    y_hat = sigmoid(h)  #シグモイド関数で計算した
    error = ans - y_hat      #誤差
    error_term = error * sigmoid_der(h) #誤差項
    del_w = lr * error_term * var                 #デルタwを求めた
    w += del_w                                          #wに数値を計算

In [72]:
w

array([-0.94586414, -0.82308945, -0.98665868,  3.74839216])